language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - php -r copy('.env.example', '.env')
    - php artisan key:generate
    - vendor/bin/phpunit --verbose
